name: run-epic
description: "Complete epic lifecycle automation: iterate through all stories not marked done in the given epic, running run-story workflow for each until epic complete or blocked"
author: "Neal Sanche"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:dev_story_location"
date: system-generated

# Workflow parameters
epic_id: "" # Optional: Epic ID (e.g., "5" for Epic 5). If empty, user will be prompted to select from available epics.
max_stories: 50 # Safety limit for story iteration
dev_model: "haiku" # Model for development tasks
review_model: "sonnet" # Model for review tasks
create_pr: true # Create pull request when epic complete

# Paths
sprint_status_file: "{project-root}/docs/sprint-artifacts/sprint-status.yaml"
workflow_status_file: "{project-root}/docs/bmm-workflow-status.yaml"

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/run-epic"
instructions: "{installed_path}/prompt.md"

standalone: true
