// lib/db/database.dart
import 'dart:io';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter/foundation.dart' show debugPrint;
import 'package:nt_helper/db/daos/metadata_dao.dart';
import 'package:nt_helper/db/daos/presets_dao.dart';
import 'package:nt_helper/db/daos/sd_cards_dao.dart';
import 'package:nt_helper/db/daos/indexed_preset_files_dao.dart';
import 'package:nt_helper/db/tables.dart';
import 'package:nt_helper/models/packed_mapping_data.dart'; // Import for converter
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
part 'database.g.dart'; // Generated by build_runner

@DriftDatabase(tables: [
  // Core Metadata
  Algorithms,
  Specifications,
  Units,
  Parameters,
  ParameterEnums,
  ParameterPages,
  ParameterPageItems,
  // Preset Data
  Presets,
  PresetSlots,
  PresetParameterValues,
  PresetParameterStringValues,
  PresetMappings,
  PresetRoutings,
  // SD Card Indexing
  SdCards,
  IndexedPresetFiles,
  // General Cache
  MetadataCache,
], daos: [
  MetadataDao,
  PresetsDao,
  SdCardsDao,
  IndexedPresetFilesDao
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 3; // Incremented schema version

  // Access DAOs (Drift generates getters)
  // MetadataDao get metadataDao => MetadataDao(this); // This getter is generated
  // PresetsDao get presetsDao => PresetsDao(this); // This getter is generated
  // FileSystemDao get fileSystemDao => FileSystemDao(this); // This getter is generated

  // --- MIGRATION LOGIC ---
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
          // Add initial data if needed
          debugPrint("Database created from scratch (version 2).");
        },
        onUpgrade: (Migrator m, int from, int to) async {
          debugPrint(
              "Starting database migration from version $from to $to...");
          // Example: Migrating FROM version 1 TO version 2 (or higher)
          if (from == 1) {
            try {
              debugPrint(
                  "Attempting to add rawUnitIndex column to parameters table...");
              await m.addColumn(parameters, parameters.rawUnitIndex);
              debugPrint(
                  "Migration successful: Added rawUnitIndex column to parameters table.");
            } catch (e) {
              debugPrint("Migration error adding rawUnitIndex column: $e");
              // Consider re-throwing or handling the error appropriately
            }
          }

          // Migration for version 3: Add SdCards and IndexedPresetFiles tables
          if (from < 3) {
            // Handles upgrades from version 1 or 2 to 3
            debugPrint(
                "Attempting to add SdCards and IndexedPresetFiles tables...");
            try {
              await m.createTable(sdCards);
              await m.createTable(indexedPresetFiles);
              debugPrint(
                  "Migration successful: Added SdCards and IndexedPresetFiles tables.");
            } catch (e) {
              debugPrint(
                  "Migration error adding SdCards/IndexedPresetFiles tables: $e");
              // Consider re-throwing or handling the error appropriately
            }
          }
          // Add more `if (from == X)` blocks for future migrations
        },
      );

// Define DAO getters
// MetadataDao get metadataDao => attachedDatabase.accessor(MetadataDao(this));
// ... other DAO getters ...
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'nt_helper_db.sqlite'));
    // Consider adding logStatements: true during development for debugging
    return NativeDatabase.createInBackground(file /*, logStatements: true*/);
  });
}
