name: run-story
description: "Complete story lifecycle automation: draft story from epic/tech-spec, context it, develop with alternating dev-story and codex-code-review cycles until done or blocked, commit changes, and update all BMAD documentation"
author: "Neal Sanche"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
story_dir: "{config_source}:dev_story_location"
date: system-generated

# Workflow parameters
story_id: "" # Optional: Full story ID (e.g., "5-2" or "e5-2-story-name"). If provided, epic_number and story_number are extracted from it.
epic_number: "" # Optional: Epic number (e.g., "4"). If empty and story_id empty, user will be prompted.
story_number: "" # Optional: Story number. If empty with epic_number, will auto-increment or prompt.
max_iterations: 20 # Safety limit for dev/review cycles
dev_model: "haiku" # Model for development tasks
review_model: "sonnet" # Model for review tasks

# Paths
sprint_status_file: "{project-root}/docs/sprint-status.yaml"
workflow_status_file: "{project-root}/docs/bmm-workflow-status.md"

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/run-story"
instructions: "{installed_path}/prompt.md"

standalone: true
