import 'package:drift/drift.dart';
import 'package:nt_helper/constants.dart';
import 'package:nt_helper/db/database.dart';
import 'package:nt_helper/db/tables.dart';
import 'package:nt_helper/domain/disting_limits.dart';
import 'package:nt_helper/models/packed_mapping_data.dart'; // For PresetMappingEntry
import 'package:collection/collection.dart'; // For groupBy, mapIndexed

part 'presets_dao.g.dart'; // Generated by build_runner

// --- Data Transfer Objects (DTOs) ---

/// Represents a complete preset with all its slots and associated data.
class FullPresetDetails {
  final PresetEntry preset;
  final List<FullPresetSlot> slots; // Sorted by slotIndex

  FullPresetDetails({required this.preset, required this.slots});
}

/// Represents a single slot within a preset, including its algorithm,
/// parameter values, mappings, routing info, and string values.
class FullPresetSlot {
  final PresetSlotEntry
  slot; // Contains slotIndex, customName, presetId, algorithmGuid
  final AlgorithmEntry algorithm; // Base algorithm metadata
  final List<int> specificationValues; // Ordered values used at instantiation
  final Map<int, int> parameterValues; // paramNum -> value
  final Map<int, String> parameterStringValues; // paramNum -> stringValue
  final Map<int, PackedMappingData> mappings; // paramNum -> mappingData
  final PresetRoutingEntry? routing;

  FullPresetSlot({
    required this.slot,
    required this.algorithm,
    this.specificationValues = const [],
    required this.parameterValues,
    required this.parameterStringValues,
    required this.mappings,
    this.routing,
  });
}

// --- DAO Definition ---

@DriftAccessor(
  tables: [
    Presets,
    PresetSlots,
    PresetSpecificationValues,
    PresetParameterValues,
    PresetMappings,
    PresetParameterStringValues,
    PresetRoutings,
    Algorithms,
  ],
)
class PresetsDao extends DatabaseAccessor<AppDatabase> with _$PresetsDaoMixin {
  PresetsDao(super.db);

  // --- Query Methods ---

  Stream<List<PresetEntry>> watchAllPresets() => select(presets).watch();

  Future<List<PresetEntry>> getAllPresets() => select(presets).get();

  Future<PresetEntry?> getPresetByName(String name) {
    return (select(
      presets,
    )..where((p) => p.name.equals(name))).getSingleOrNull();
  }

  Future<PresetEntry?> getPresetById(int id) {
    return (select(presets)..where((p) => p.id.equals(id))).getSingleOrNull();
  }

  Future<List<FullPresetDetails>> getTemplates() async {
    final templatePresets =
        await (select(presets)
              ..where((p) => p.isTemplate.equals(true))
              ..where(
                (p) =>
                    p.category.isNull() |
                    p.category.isNotValue(Constants.algorithmClipboardCategory),
              )
              ..orderBy([(p) => OrderingTerm.asc(p.name)]))
            .get();
    final List<FullPresetDetails> templates = [];
    for (final preset in templatePresets) {
      final details = await getFullPresetDetails(preset.id);
      if (details != null) {
        templates.add(details);
      }
    }
    return templates;
  }

  Stream<int> watchTemplateCount() {
    final query = selectOnly(presets)
      ..addColumns([presets.id.count()])
      ..where(presets.isTemplate.equals(true));
    return query.map((row) => row.read(presets.id.count()) ?? 0).watchSingle();
  }

  Future<List<FullPresetDetails>> getNonTemplates() async {
    final nonTemplatePresets = await (select(
      presets,
    )..where((p) => p.isTemplate.equals(false))).get();
    final List<FullPresetDetails> nonTemplates = [];
    for (final preset in nonTemplatePresets) {
      final details = await getFullPresetDetails(preset.id);
      if (details != null) {
        nonTemplates.add(details);
      }
    }
    return nonTemplates;
  }

  Future<FullPresetDetails?> getFullPresetDetails(int presetId) async {
    final presetEntry = await (select(
      presets,
    )..where((p) => p.id.equals(presetId))).getSingleOrNull();

    if (presetEntry == null) return null;

    try {
      // Fetch all slots for the preset
      final slotEntries = await (select(
        presetSlots,
      )..where((s) => s.presetId.equals(presetId))).get();

      if (slotEntries.isEmpty) {
        return FullPresetDetails(preset: presetEntry, slots: []);
      }

      final slotIds = slotEntries.map((s) => s.id).toList();
      final algorithmGuids = slotEntries
          .map((s) => s.algorithmGuid)
          .toSet(); // Use Set for efficiency

      // Fetch required related data in batches
      final algorithmsQuery = select(algorithms)
        ..where((a) => a.guid.isIn(algorithmGuids));
      final algorithmsMap = {
        for (var a in await algorithmsQuery.get()) a.guid: a,
      };

      // Fetch per-slot algorithm specification values.
      final specificationValuesQuery = select(presetSpecificationValues)
        ..where((v) => v.presetSlotId.isIn(slotIds));
      final specificationValueEntries = await specificationValuesQuery.get();
      final specificationValuesBySlot =
          groupBy<PresetSpecificationValueEntry, int>(
            specificationValueEntries,
            (v) => v.presetSlotId,
          ).map((slotId, entries) {
            entries.sort(
              (a, b) => a.specificationIndex.compareTo(b.specificationIndex),
            );
            return MapEntry(
              slotId,
              entries.map((entry) => entry.value).toList(growable: false),
            );
          });

      // Fetch parameter values
      final valuesQuery = select(presetParameterValues)
        ..where((v) => v.presetSlotId.isIn(slotIds));
      final valueEntries = await valuesQuery.get();
      final paramValuesBySlot =
          groupBy<PresetParameterValueEntry, int>(
            valueEntries,
            (v) => v.presetSlotId,
          ).map(
            (slotId, entries) => MapEntry(slotId, {
              for (var e in entries) e.parameterNumber: e.value,
            }),
          );

      // Fetch parameter string values
      final stringValuesQuery =
          select(presetParameterStringValues) // Use generated reference
            ..where((sv) => sv.presetSlotId.isIn(slotIds));
      final stringValueEntries = await stringValuesQuery.get();
      final paramStringValuesBySlot =
          groupBy<PresetParameterStringValueEntry, int>(
            stringValueEntries,
            (sv) => sv.presetSlotId,
          ).map(
            (slotId, entries) => MapEntry(slotId, {
              for (var e in entries) e.parameterNumber: e.stringValue,
            }),
          );

      // Fetch mappings
      final mappingsQuery = select(presetMappings)
        ..where((m) => m.presetSlotId.isIn(slotIds));
      final mappingEntries = await mappingsQuery.get();
      final paramMappingsBySlot =
          groupBy<PresetMappingEntry, int>(
            mappingEntries,
            (m) => m.presetSlotId,
          ).map(
            (slotId, entries) => MapEntry(slotId, {
              for (var e in entries)
                e.parameterNumber: e.packedData.copyWith(
                  perfPageIndex: e.perfPageIndex,
                ),
            }),
          );

      // Fetch routing information
      final routingsQuery = select(presetRoutings)
        ..where((r) => r.presetSlotId.isIn(slotIds));
      final routingEntries = await routingsQuery.get();
      final routingBySlot = {
        for (final routing in routingEntries) routing.presetSlotId: routing,
      };

      // Assemble FullPresetSlot list
      final List<FullPresetSlot> fullSlots = [];
      for (final slotEntry in slotEntries) {
        final algorithm = algorithmsMap[slotEntry.algorithmGuid];
        if (algorithm != null) {
          final slotId = slotEntry.id;
          fullSlots.add(
            FullPresetSlot(
              slot: slotEntry,
              algorithm: algorithm,
              specificationValues:
                  specificationValuesBySlot[slotId] ?? const [],
              parameterValues: paramValuesBySlot[slotId] ?? {},
              parameterStringValues: paramStringValuesBySlot[slotId] ?? {},
              mappings: paramMappingsBySlot[slotId] ?? {},
              routing: routingBySlot[slotId],
            ),
          );
        } else {
          // Handle missing algorithm metadata gracefully (e.g., skip slot or error)
        }
      }

      // Sort slots by slotIndex using standard sort
      fullSlots.sort((a, b) => a.slot.slotIndex.compareTo(b.slot.slotIndex));

      return FullPresetDetails(preset: presetEntry, slots: fullSlots);
    } catch (e) {
      return null;
    }
  }

  // --- Algorithm Clipboard ---

  /// The algorithm clipboard is a single reserved system template (see
  /// [Constants.algorithmClipboardPresetName]) used by the Mod+C / Mod+V
  /// slot copy/paste flow. It is persisted so it survives app restarts but is
  /// hidden from the Template Manager via [getTemplates].

  /// Returns the clipboard template with all its slots, or `null` when the
  /// clipboard is empty (no reserved row exists yet).
  Future<FullPresetDetails?> getClipboardTemplate() async {
    final row = await _clipboardPresetRow();
    if (row == null) return null;
    return getFullPresetDetails(row.id);
  }

  /// Returns the number of slots currently stored in the clipboard, or `0`
  /// when the clipboard is empty.
  Future<int> clipboardSlotCount() async {
    final row = await _clipboardPresetRow();
    if (row == null) return 0;
    final count = await (select(
      presetSlots,
    )..where((s) => s.presetId.equals(row.id))).map((s) => 1).get();
    return count.length;
  }

  /// Upserts [details] as the clipboard template, replacing any prior
  /// clipboard contents. The preset row is pinned to the reserved name and
  /// category; its slots (algorithms + values + mappings + routings) are
  /// copied verbatim from [details]. Returns the clipboard preset id.
  Future<int> saveClipboardTemplate(FullPresetDetails details) async {
    final existing = await _clipboardPresetRow();
    final pinned = details.preset.copyWith(
      id: existing?.id ?? -1,
      name: Constants.algorithmClipboardPresetName,
      category: Value(Constants.algorithmClipboardCategory),
      isTemplate: true,
      templateMetadata: const Value(null),
    );
    final reindexed = FullPresetDetails(
      preset: pinned,
      slots: [
        for (var i = 0; i < details.slots.length; i++)
          _reindexClipboardSlot(details.slots[i], i),
      ],
    );
    return saveFullPreset(reindexed, isTemplate: true);
  }

  /// Deletes the clipboard template, if any. Safe to call when the clipboard
  /// is already empty.
  Future<void> clearClipboardTemplate() async {
    final row = await _clipboardPresetRow();
    if (row != null) {
      await deletePreset(row.id);
    }
  }

  Future<PresetEntry?> _clipboardPresetRow() {
    return (select(presets)
          ..where((p) => p.isTemplate.equals(true))
          ..where(
            (p) =>
                p.name.equals(Constants.algorithmClipboardPresetName) &
                p.category.equals(Constants.algorithmClipboardCategory),
          ))
        .getSingleOrNull();
  }

  FullPresetSlot _reindexClipboardSlot(FullPresetSlot slot, int newIndex) {
    return FullPresetSlot(
      slot: slot.slot.copyWith(id: -1, presetId: -1, slotIndex: newIndex),
      algorithm: slot.algorithm,
      specificationValues: slot.specificationValues,
      parameterValues: slot.parameterValues,
      parameterStringValues: slot.parameterStringValues,
      mappings: slot.mappings,
      routing: slot.routing,
    );
  }

  // --- Insertion/Update Methods ---

  /// Saves a complete preset structure (insert or update).
  /// Handles saving the preset entry, slots, values, mappings, routing, and string values.
  /// Returns the ID of the saved/updated preset.
  Future<int> saveFullPreset(
    FullPresetDetails details, {
    bool isTemplate = false,
  }) async {
    return transaction(() async {
      // 1. Upsert Preset Entry
      final presetCompanion = details.preset
          .toCompanion(true) // Convert PresetEntry to its companion
          // Explicitly handle the ID: if it's -1, treat it as absent for auto-increment.
          // Otherwise, use the provided ID for potential replacement.
          .copyWith(
            id: details.preset.id == -1
                ? const Value.absent()
                : Value(details.preset.id),
            lastModified: Value(DateTime.now()),
            isTemplate: Value(isTemplate),
          );

      // Insert the companion. `insertOrReplace` will:
      // - Insert if `id` is absent (and generate a new ID).
      // - Replace if `id` is present and matches an existing row.
      final presetId = await into(presets).insert(
        presetCompanion,
        mode:
            InsertMode.insertOrReplace, // Handles insert or update based on ID
      );

      // --- Check if insert returned a valid ID ---
      // SQLite rowid starts at 1. If we get 0 or less, something went wrong.
      if (presetId <= 0) {
        // Throw an exception if the insert/replace failed to return a valid ID.
        // This should cause the transaction to roll back.
        throw Exception(
          "Database operation failed: Invalid preset ID returned ($presetId)",
        );
      }
      // --- End Check ---

      // 2. Handle Slots
      final existingSlots = await (select(
        presetSlots,
      )..where((s) => s.presetId.equals(presetId))).get();
      final Map<int, PresetSlotEntry> existingSlotsById = {
        for (var s in existingSlots) s.id: s,
      };
      final Set<int> incomingSlotIds = {};

      for (final fullSlot in details.slots) {
        PresetSlotEntry? existingSlotForIndex;
        for (var es in existingSlotsById.values) {
          if (es.slotIndex == fullSlot.slot.slotIndex) {
            existingSlotForIndex = es;
            break;
          }
        }

        // Upsert slot entry using companion constructor
        final slotCompanion = PresetSlotsCompanion(
          presetId: Value(presetId),
          slotIndex: Value(fullSlot.slot.slotIndex),
          algorithmGuid: Value(fullSlot.slot.algorithmGuid),
          customName: Value(fullSlot.slot.customName),
          id: existingSlotForIndex != null
              ? Value(existingSlotForIndex.id)
              : const Value.absent(),
        );
        final slotId = await into(
          presetSlots,
        ).insert(slotCompanion, mode: InsertMode.insertOrReplace);
        incomingSlotIds.add(slotId);

        // Clear existing related data for this slot
        await batch((batch) {
          batch.deleteWhere(
            presetSpecificationValues,
            (row) => row.presetSlotId.equals(slotId),
          );
          batch.deleteWhere(
            presetParameterValues,
            (row) => row.presetSlotId.equals(slotId),
          );
          batch.deleteWhere(
            presetParameterStringValues,
            (row) => row.presetSlotId.equals(slotId),
          );
          batch.deleteWhere(
            presetMappings,
            (row) => row.presetSlotId.equals(slotId),
          );
          batch.deleteWhere(
            presetRoutings,
            (row) => row.presetSlotId.equals(slotId),
          );
        });

        // Batch insert new data using .insert() companions
        await batch((batch) {
          if (fullSlot.specificationValues.isNotEmpty) {
            batch.insertAll(
              presetSpecificationValues,
              fullSlot.specificationValues.indexed
                  .map(
                    (entry) => PresetSpecificationValuesCompanion.insert(
                      presetSlotId: slotId,
                      specificationIndex: entry.$1,
                      value: entry.$2,
                    ),
                  )
                  .toList(),
            );
          }
          if (fullSlot.parameterValues.isNotEmpty) {
            batch.insertAll(
              presetParameterValues,
              fullSlot.parameterValues.entries
                  .map(
                    (e) => PresetParameterValuesCompanion.insert(
                      presetSlotId: slotId,
                      parameterNumber: e.key,
                      value: e.value,
                    ),
                  )
                  .toList(),
            );
          }
          if (fullSlot.parameterStringValues.isNotEmpty) {
            batch.insertAll(
              presetParameterStringValues,
              fullSlot.parameterStringValues.entries
                  .map(
                    (e) => PresetParameterStringValuesCompanion.insert(
                      presetSlotId: slotId,
                      parameterNumber: e.key,
                      stringValue: e.value,
                    ),
                  )
                  .toList(),
            );
          }
          if (fullSlot.mappings.isNotEmpty) {
            batch.insertAll(
              presetMappings,
              fullSlot.mappings.entries
                  .map(
                    (e) => PresetMappingsCompanion.insert(
                      presetSlotId: slotId,
                      parameterNumber: e.key,
                      packedData: e.value,
                      perfPageIndex: Value(e.value.perfPageIndex),
                    ),
                  )
                  .toList(),
            );
          }
          if (fullSlot.routing != null) {
            batch.insert(
              presetRoutings,
              PresetRoutingsCompanion.insert(
                presetSlotId: Value(slotId),
                routingInfoJson: fullSlot.routing!.routingInfoJson,
              ),
            );
          }
        });
      }

      // 4. Delete slots (and their cascaded data) that were in the DB but not in the incoming details
      final Set<int> existingSlotIdsSet = existingSlotsById.keys.toSet();
      final slotsToDelete = existingSlotIdsSet.difference(incomingSlotIds);
      if (slotsToDelete.isNotEmpty) {
        await (delete(
          presetSpecificationValues,
        )..where((v) => v.presetSlotId.isIn(slotsToDelete))).go();
        await (delete(
          presetSlots,
        )..where((s) => s.id.isIn(slotsToDelete))).go();
      }

      return presetId;
    });
  }

  Future<void> updatePresetName(int presetId, String newName) async {
    await (update(presets)..where((p) => p.id.equals(presetId))).write(
      PresetsCompanion(
        name: Value(newName),
        lastModified: Value(DateTime.now()),
      ),
    );
  }

  Future<void> updateTemplateMetadata({
    required int presetId,
    required String name,
    required String? category,
    required String? templateMetadata,
  }) async {
    await (update(presets)..where((p) => p.id.equals(presetId))).write(
      PresetsCompanion(
        name: Value(name),
        category: Value(category),
        templateMetadata: Value(templateMetadata),
        lastModified: Value(DateTime.now()),
      ),
    );
  }

  Future<void> toggleTemplateStatus(int presetId, bool newStatus) async {
    await (update(presets)..where((p) => p.id.equals(presetId))).write(
      PresetsCompanion(
        isTemplate: Value(newStatus),
        lastModified: Value(DateTime.now()),
      ),
    );
  }

  /// Updates the performance page index for a specific parameter in a preset slot.
  ///
  /// - [presetSlotId]: The ID of the preset slot (from PresetSlots table)
  /// - [parameterNumber]: The parameter number within the algorithm
  /// - [perfPageIndex]: The performance page index (0-30, where 0 = not assigned)
  Future<void> updatePerformancePageIndex({
    required int presetSlotId,
    required int parameterNumber,
    required int perfPageIndex,
  }) async {
    // Update the perfPageIndex column in the presetMappings table
    await (update(presetMappings)
          ..where((m) => m.presetSlotId.equals(presetSlotId))
          ..where((m) => m.parameterNumber.equals(parameterNumber)))
        .write(PresetMappingsCompanion(perfPageIndex: Value(perfPageIndex)));
  }

  // --- Deletion Methods ---

  Future<void> deletePreset(int presetId) => transaction(() async {
    final slotIds =
        await (select(presetSlots)
              ..where((slot) => slot.presetId.equals(presetId)))
            .map((slot) => slot.id)
            .get();
    if (slotIds.isNotEmpty) {
      await (delete(
        presetSpecificationValues,
      )..where((value) => value.presetSlotId.isIn(slotIds))).go();
    }
    await (delete(presets)..where((p) => p.id.equals(presetId))).go();
    // Note: Cascading deletes in the table definitions should handle related data
    // (PresetSlots -> PresetParameterValues, PresetParameterStringValues, PresetMappings, PresetRoutings)
  });

  /// Copies a subset of slots from `templateId` into `targetPresetId`.
  ///
  /// See [ApplyTemplateSlotsResult] for the result shape and the spec in
  /// `specs/2026-05-22_multi-algorithm-templates.md` for the full semantics.
  Future<ApplyTemplateSlotsResult> applyTemplateSlots({
    required int templateId,
    required int targetPresetId,
    required List<int> templateSlotIndices,
    required int insertionOffset,
    bool overwrite = false,
  }) async {
    if (templateSlotIndices.isEmpty) {
      throw ArgumentError.value(
        templateSlotIndices,
        'templateSlotIndices',
        'must not be empty',
      );
    }
    if (insertionOffset < 0) {
      throw ArgumentError.value(
        insertionOffset,
        'insertionOffset',
        'must be >= 0',
      );
    }

    return transaction(() async {
      final templateExists = await (select(
        presets,
      )..where((p) => p.id.equals(templateId))).getSingleOrNull();
      if (templateExists == null) {
        throw StateError('Template preset $templateId not found.');
      }
      final targetExists = await (select(
        presets,
      )..where((p) => p.id.equals(targetPresetId))).getSingleOrNull();
      if (targetExists == null) {
        throw StateError('Target preset $targetPresetId not found.');
      }

      // Snapshot the template's slot rows in slotIndex order so we can map
      // requested indices to source rows.
      final templateSlotRows =
          await (select(presetSlots)
                ..where((s) => s.presetId.equals(templateId))
                ..orderBy([(s) => OrderingTerm.asc(s.slotIndex)]))
              .get();

      for (final i in templateSlotIndices) {
        if (i < 0 || i >= templateSlotRows.length) {
          throw ArgumentError.value(
            i,
            'templateSlotIndices',
            'index out of range [0, ${templateSlotRows.length})',
          );
        }
      }

      // Snapshot child rows for the template's slots, keyed by source slot id.
      final templateSlotIds = templateSlotRows
          .map((s) => s.id)
          .toList(growable: false);
      final tmplSpecificationValues = templateSlotIds.isEmpty
          ? <PresetSpecificationValueEntry>[]
          : await (select(
              presetSpecificationValues,
            )..where((v) => v.presetSlotId.isIn(templateSlotIds))).get();
      final tmplValues = templateSlotIds.isEmpty
          ? <PresetParameterValueEntry>[]
          : await (select(
              presetParameterValues,
            )..where((v) => v.presetSlotId.isIn(templateSlotIds))).get();
      final tmplStrings = templateSlotIds.isEmpty
          ? <PresetParameterStringValueEntry>[]
          : await (select(
              presetParameterStringValues,
            )..where((v) => v.presetSlotId.isIn(templateSlotIds))).get();
      final tmplMappings = templateSlotIds.isEmpty
          ? <PresetMappingEntry>[]
          : await (select(
              presetMappings,
            )..where((m) => m.presetSlotId.isIn(templateSlotIds))).get();
      final tmplRoutings = templateSlotIds.isEmpty
          ? <PresetRoutingEntry>[]
          : await (select(
              presetRoutings,
            )..where((r) => r.presetSlotId.isIn(templateSlotIds))).get();

      final tmplValuesBySlot = <int, List<PresetParameterValueEntry>>{};
      final tmplSpecificationValuesBySlot =
          <int, List<PresetSpecificationValueEntry>>{};
      for (final value in tmplSpecificationValues) {
        tmplSpecificationValuesBySlot
            .putIfAbsent(value.presetSlotId, () => [])
            .add(value);
      }
      for (final v in tmplValues) {
        tmplValuesBySlot.putIfAbsent(v.presetSlotId, () => []).add(v);
      }
      final tmplStringsBySlot = <int, List<PresetParameterStringValueEntry>>{};
      for (final v in tmplStrings) {
        tmplStringsBySlot.putIfAbsent(v.presetSlotId, () => []).add(v);
      }
      final tmplMappingsBySlot = <int, List<PresetMappingEntry>>{};
      for (final m in tmplMappings) {
        tmplMappingsBySlot.putIfAbsent(m.presetSlotId, () => []).add(m);
      }
      final tmplRoutingBySlot = <int, PresetRoutingEntry>{};
      for (final r in tmplRoutings) {
        tmplRoutingBySlot[r.presetSlotId] = r;
      }

      // Resolve which algorithm GUIDs are locally known.
      final neededGuids = {
        for (final i in templateSlotIndices) templateSlotRows[i].algorithmGuid,
      };
      final knownAlgoRows = neededGuids.isEmpty
          ? <AlgorithmEntry>[]
          : await (select(
              algorithms,
            )..where((a) => a.guid.isIn(neededGuids))).get();
      final knownGuids = knownAlgoRows.map((a) => a.guid).toSet();

      // Build the apply plan: keep templateSlotIndices in order; split into
      // applied vs skipped.
      final appliedSourceRows = <PresetSlotEntry>[];
      final skipped = <int>[];
      final missingGuids = <String>{};
      for (final i in templateSlotIndices) {
        final row = templateSlotRows[i];
        if (knownGuids.contains(row.algorithmGuid)) {
          appliedSourceRows.add(row);
        } else {
          skipped.add(i);
          missingGuids.add(row.algorithmGuid);
        }
      }
      final appliedCount = appliedSourceRows.length;

      // Target slot space accounting.
      final existingTargetSlots =
          await (select(presetSlots)
                ..where((s) => s.presetId.equals(targetPresetId))
                ..orderBy([(s) => OrderingTerm.asc(s.slotIndex)]))
              .get();
      final existingCount = existingTargetSlots.length;
      final clampedOffset = insertionOffset > existingCount
          ? existingCount
          : insertionOffset;

      const slotLimit = DistingLimits.maxPresetSlots;
      // Space accounting uses the *unclamped* insertionOffset in replace mode
      // so that a caller asking to "replace at slot 25" of a 5-slot target
      // (which would need 35 slots) fails the limit check explicitly, instead
      // of silently being treated as "append starting at slot 5".
      final spaceNeeded = overwrite
          ? (insertionOffset + appliedCount > existingCount
                ? insertionOffset + appliedCount
                : existingCount)
          : existingCount + appliedCount;
      if (appliedCount > 0 && spaceNeeded > slotLimit) {
        throw TemplateSpaceException(
          current: existingCount,
          applied: appliedCount,
          limit: slotLimit,
        );
      }

      // Mutation phase.
      if (overwrite) {
        // For each i in 0..appliedCount-1, replace the target slot at
        // clampedOffset+i (or create it if absent).
        for (var i = 0; i < appliedCount; i++) {
          final targetSlotIndex = clampedOffset + i;
          final existing = existingTargetSlots.firstWhereOrNull(
            (s) => s.slotIndex == targetSlotIndex,
          );
          if (existing != null) {
            // Explicitly clear non-cascading children (PresetRoutings) and
            // cascading ones too (the slot row will be replaced).
            await (delete(
              presetSpecificationValues,
            )..where((v) => v.presetSlotId.equals(existing.id))).go();
            await (delete(
              presetMappings,
            )..where((m) => m.presetSlotId.equals(existing.id))).go();
            await (delete(
              presetRoutings,
            )..where((r) => r.presetSlotId.equals(existing.id))).go();
            await (delete(
              presetSlots,
            )..where((s) => s.id.equals(existing.id))).go();
          }
        }
      } else {
        // Insert mode: shift any existing slots at clampedOffset..end upward
        // by appliedCount. Shift from top down to avoid uniqueness clashes.
        if (appliedCount > 0) {
          final toShift =
              existingTargetSlots
                  .where((s) => s.slotIndex >= clampedOffset)
                  .toList()
                ..sort((a, b) => b.slotIndex.compareTo(a.slotIndex));
          for (final row in toShift) {
            await (update(
              presetSlots,
            )..where((s) => s.id.equals(row.id))).write(
              PresetSlotsCompanion(
                slotIndex: Value(row.slotIndex + appliedCount),
              ),
            );
          }
        }
      }

      // Copy each applied template slot into the target preset.
      final insertedSlotIndices = <int>[];
      for (var i = 0; i < appliedCount; i++) {
        final source = appliedSourceRows[i];
        final newSlotIndex = clampedOffset + i;
        final newSlotId = await into(presetSlots).insert(
          PresetSlotsCompanion.insert(
            presetId: targetPresetId,
            slotIndex: newSlotIndex,
            algorithmGuid: source.algorithmGuid,
            customName: Value(source.customName),
          ),
        );
        insertedSlotIndices.add(newSlotIndex);

        final srcSpecificationValues =
            tmplSpecificationValuesBySlot[source.id] ?? const [];
        if (srcSpecificationValues.isNotEmpty) {
          await batch((b) {
            b.insertAll(
              presetSpecificationValues,
              srcSpecificationValues
                  .map(
                    (value) => PresetSpecificationValuesCompanion.insert(
                      presetSlotId: newSlotId,
                      specificationIndex: value.specificationIndex,
                      value: value.value,
                    ),
                  )
                  .toList(growable: false),
            );
          });
        }
        final srcValues = tmplValuesBySlot[source.id] ?? const [];
        if (srcValues.isNotEmpty) {
          await batch((b) {
            b.insertAll(
              presetParameterValues,
              srcValues
                  .map(
                    (v) => PresetParameterValuesCompanion.insert(
                      presetSlotId: newSlotId,
                      parameterNumber: v.parameterNumber,
                      value: v.value,
                    ),
                  )
                  .toList(growable: false),
            );
          });
        }
        final srcStrings = tmplStringsBySlot[source.id] ?? const [];
        if (srcStrings.isNotEmpty) {
          await batch((b) {
            b.insertAll(
              presetParameterStringValues,
              srcStrings
                  .map(
                    (v) => PresetParameterStringValuesCompanion.insert(
                      presetSlotId: newSlotId,
                      parameterNumber: v.parameterNumber,
                      stringValue: v.stringValue,
                    ),
                  )
                  .toList(growable: false),
            );
          });
        }
        final srcMappings = tmplMappingsBySlot[source.id] ?? const [];
        if (srcMappings.isNotEmpty) {
          await batch((b) {
            b.insertAll(
              presetMappings,
              srcMappings
                  .map(
                    (m) => PresetMappingsCompanion.insert(
                      presetSlotId: newSlotId,
                      parameterNumber: m.parameterNumber,
                      packedData: m.packedData,
                      perfPageIndex: Value(m.perfPageIndex),
                    ),
                  )
                  .toList(growable: false),
            );
          });
        }
        final srcRouting = tmplRoutingBySlot[source.id];
        if (srcRouting != null) {
          await into(presetRoutings).insert(
            PresetRoutingsCompanion.insert(
              presetSlotId: Value(newSlotId),
              routingInfoJson: srcRouting.routingInfoJson,
            ),
          );
        }
      }

      // Bump target lastModified.
      await (update(presets)..where((p) => p.id.equals(targetPresetId))).write(
        PresetsCompanion(lastModified: Value(DateTime.now())),
      );

      String? warning;
      if (skipped.isNotEmpty) {
        final missingList = missingGuids.toList()..sort();
        warning =
            'Skipped ${skipped.length} template slot(s) with missing algorithm '
            'metadata: ${missingList.join(', ')}.';
      }

      return ApplyTemplateSlotsResult(
        targetPresetId: targetPresetId,
        insertedSlotIndices: List.unmodifiable(insertedSlotIndices),
        skippedTemplateSlotIndices: List.unmodifiable(skipped),
        warning: warning,
      );
    });
  }
}

/// Outcome of [PresetsDao.applyTemplateSlots].
class ApplyTemplateSlotsResult {
  final int targetPresetId;

  /// New `slotIndex` values produced in the target preset, in apply order.
  final List<int> insertedSlotIndices;

  /// Indices from the original `templateSlotIndices` argument that were
  /// skipped — typically because the source slot's algorithm GUID has no
  /// matching row in the local `algorithms` table.
  final List<int> skippedTemplateSlotIndices;

  /// User-facing, non-fatal warning. Null when nothing was skipped.
  final String? warning;

  const ApplyTemplateSlotsResult({
    required this.targetPresetId,
    required this.insertedSlotIndices,
    required this.skippedTemplateSlotIndices,
    this.warning,
  });
}

/// Thrown by [PresetsDao.applyTemplateSlots] when the target would exceed
/// the device's preset slot limit.
class TemplateSpaceException implements Exception {
  /// Existing slot count on the target preset before the apply.
  final int current;

  /// Number of slots the apply would add (after skipping any with missing
  /// algorithm metadata).
  final int applied;

  /// Hard upper bound. Defaults to the device limit.
  final int limit;

  TemplateSpaceException({
    required this.current,
    required this.applied,
    this.limit = DistingLimits.maxPresetSlots,
  });

  @override
  String toString() =>
      'TemplateSpaceException: Cannot apply: $current + $applied > $limit slots';
}
