name: develop-epic
description: "Orchestrates epic development by executing workflow-status NEXT_COMMAND actions until epic complete or blocked"
author: "Neal Sanche"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# Workflow parameters
epic_number: "" # Required: Epic number to develop (e.g., "4")
status_file: "{project-root}/docs/bmm-workflow-status.md"
max_iterations: 10 # Safety limit for autonomous loops
dev_model: "haiku" # Model for development tasks
review_model: "sonnet" # Model for review tasks

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/4-implementation/develop-epic"
instructions: "{installed_path}/prompt.md"

standalone: true
