name: iOS Build and Sign

on:
  push:
    tags:
      - "v*" # e.g., v1.0, v1.2.3, etc.
    branches:
      - ios-build

jobs:
  build-ios:
    runs-on: macos-15
    name: Build & Sign iOS

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print macOS & Xcode info (debug)
        run: |
          echo "macOS version:"
          sw_vers
          echo "Xcode version:"
          xcodebuild -version
          echo "Environment variables (sorted):"
          env | sort

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.2"

      - name: Flutter Doctor (debug)
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Decode iOS certificate from Base64
        run: echo "${{ secrets.APPLE_CERTIFICATES }}" | base64 --decode > apple_certificates.p12

      - name: Decode provisioning profile from Base64
        run: echo "${{ secrets.APP_STORE_MOBILEPROVISION }}" | base64 --decode > distribution.mobileprovision

      - name: Debug list files
        run: |
          echo "Files in workspace:"
          ls -la
          echo "Certificate details:"
          ls -la apple_certificates.p12 || true
          echo "Provisioning profile details:"
          ls -la distribution.mobileprovision || true

      - name: Create & unlock keychain
        run: |
          KEYCHAIN_NAME="build.keychain"
          KEYCHAIN_PASSWORD=""  # or set one if you prefer

          echo "Creating keychain..."
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"

          # Keep the keychain unlocked for a while:
          security set-keychain-settings -lut 21600 "$KEYCHAIN_NAME"

          echo "Unlocking keychain..."
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"

          echo "Setting $KEYCHAIN_NAME as default..."
          security default-keychain -s "$KEYCHAIN_NAME"

          echo "List of keychains now:"
          security list-keychains
        shell: bash

      - name: Import certificate
        run: |
          KEYCHAIN_NAME="build.keychain"

          # The password for your .p12 is in APPLE_CERTIFICATES_PASSWORD:
          security import apple_certificates.p12 \
            -k "$KEYCHAIN_NAME" \
            -P "${{ secrets.APPLE_CERTIFICATES_PASSWORD }}" \
            -T /usr/bin/codesign

          # Give codesign tools permission
          security set-key-partition-list -S apple-tool:,apple: -k "" "$KEYCHAIN_NAME"

          echo "Identities in keychain:"
          security find-identity -v -p codesigning "$KEYCHAIN_NAME" || true

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp distribution.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "Provisioning profiles in that folder:"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Download iOS 18 SDK
        run: sudo xcodebuild -downloadPlatform iOS

      - name: Flutter build IPA
        run: |
          set -x
          flutter clean
          flutter pub get
          flutter build ipa --export-options-plist=ios/ExportOptions.plist

      - name: Debug List final artifacts
        run: ls -R build/ios/ipa || true

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app \
            --type ios \
            --file "./build/ios/ipa/nt_helper.ipa" \
            --username "${{ secrets.MACOS_APPLE_ID }}" \
            --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" \
            --verbose

      - name: Delete temporary keychain
        if: always() # ensures this step runs regardless of success/failure above
        run: |
          security delete-keychain build.keychain
